language: java
jdk:
- openjdk8

#branches:
#  only:
#   - master


notifications:
  email:
    recipients:
    - magzhan.karasayev@allpay.kz
    - sanzhar.aubakirov@innoforce.kz
    on_success: change
    on_failure: always

install: mvn clean install -B -V